# Generated by Django 3.2.5 on 2021-08-12 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0004_alter_author_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='note',
            new_name='notes',
        ),
    ]
